### ISSUE TITLE
awsm.css Styling

### ISSUE THREAD

**Issue by dgilleland** [CPSC-1517/cpsc-1517-workbook-may-2021-dgilleland#10]
# Using `awsm.css` 

Styling your site is up to you. However, if you decide to _not_ use Bootstrap, it is recommended that you remove the contents of the `wwwroot\lib\` folder and modify the following *cshtml* pages to clean up your use of the `class=""` attributes in the HTML.

## Using LibMan

[**LibMan**](https://docs.microsoft.com/aspnet/core/client-side/libman/) is a tool to manage client-side libraries in an ASP.NET Core application. It's a recommended tool to use because it works cleanly with web applications in .NET Core (as opposed to trying to use *npm* along with other package managers that are geared toward *node* applications).

Instructions on [installing and using LibMan from the command line can be found on the Microsoft Docs site](https://docs.microsoft.com/aspnet/core/client-side/libman/libman-cli) (handy if you are working in VS Code). For using LibMan in Visual Studio 2019

### Installing AWSM.CSS

```ps
libman install awsm.css --provider unpkg
```

If you use the **awsm.css** library, you can bring in the stylesheet by placing code similar to the following in your `_Layout.cshtml` file's `<header>` tag. The awsm.css library also comes with various themes.

```html
<link href="/lib/awsm.css/dist/awsm.min.css" rel="stylesheet">
```

### `site.css`

Here's a sample bit of styling you can place in your `site.css` file to replace its existing content. This styling increases the width and adds some menu styling based on awsm.

```css
body {
    max-width: 100%;
    margin: 0;
    padding: 0;
}

    body header, body main, body footer, body article {
        position: relative;
        max-width: 100%;
        margin: 0 10rem;
    }

    body > header {
        max-width: 100%;
        margin: 0;
    }

        body > header > nav {
            /* Include if you have multiple <ul> children 
            display: grid;
            grid-template-columns: auto 80rem auto; 
            */
            background-color: black;
            color: white;
            margin-top: 0;
            margin-bottom: 0;
        }

            body > header > nav > ul {
              max-width: 100%;
              margin: 0 10rem 1rem 10rem;
              padding-top: 1rem;
              min-height: 3rem;
            }

nav > ul > li {
    margin-top: 0.25em;
}

body > header a, body > header a:visited {
    color: whitesmoke;
    font-weight: bold;
    text-decoration: none;
}

header > figure {
    height: 200px;
    overflow: hidden;
    margin-top: 0;
}

footer a {
    text-decoration: none;
}

header > nav > ul:last-child {
    text-align: right;
}

header > nav > ul:last-child {
  text-align: left;
}

main > *:first-child {
    margin-top: 1rem;
}

form {
    margin-left: 0;
}
form label > select {
    display: inline-block;
}
```

## Clean `_Layout.cshtml`

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <!-- Your preferred stylesheet library here -->
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav>
            <ul>
                <li><a asp-area="" asp-page="/Index">WebApp</a></li>
                <li><a asp-area="" asp-page="/Privacy">Privacy</a></li>
            </ul>
        </nav>
    </header>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer>
        <div>
            &copy; 2021 - WebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Your preferred javascript library here -->
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>
```

## Clean `Index.cshtml`

```html
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1>Welcome</h1>
<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
```

## Clean `Error.cshtml`

```html
@page
@model ErrorModel
@{
    ViewData["Title"] = "Error";
}

<header>
    <h1>Error.</h1>
    <h2>An error occurred while processing your request.</h2>
</header>

@if (Model.ShowRequestId)
{
    <p>
        <strong>Request ID:</strong> <code>@Model.RequestId</code>
    </p>
}

<h3>Development Mode</h3>
<p>
    Swapping to the <strong>Development</strong> environment displays detailed information about the error that occurred.
</p>
<p>
    <strong>The Development environment shouldn't be enabled for deployed applications.</strong>
    It can result in displaying sensitive information from exceptions to end users.
    For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong>
    and restarting the app.
</p>
```

----
